Repository score-json/json, pull requests merged in 2025-09, with the labels that each got.

#69 trustable: Update trudag tooling scripts and cleanup of redundant generated code
  .github/workflows/publish_documentation.yml
  TSF/scripts/clean_trudag_output.py
  TSF/scripts/generate_documentation.sh
  TSF/scripts/generate_report.sh
  TSF/tests/unit-class_parser_core.cpp
  TSF/trustable/TRUSTABLE-SOFTWARE.md
  TSF/trustable/assertions/TA-BEHAVIOURS.md
  TSF/trustable/assertions/TA-CONFIDENCE.md
  TSF/trustable/assertions/TA-CONSTRAINTS.md
  TSF/trustable/assertions/TA-INPUTS.md
  TSF/trustable/assertions/TA-ITERATIONS.md
  TSF/trustable/assertions/TA-METHODOLOGIES.md
  TSF/trustable/assertions/TA-MISBEHAVIOURS.md
  TSF/trustable/assertions/TA-RELEASES.md
  TSF/trustable/assertions/TA-SUPPLY_CHAIN.md
  TSF/trustable/assertions/TA-TESTS.md
  TSF/trustable/assertions/TA-UPDATES.md
  TSF/trustable/assumptions-of-use/AOU-01.md
  TSF/trustable/assumptions-of-use/AOU-02.md
  TSF/trustable/assumptions-of-use/AOU-04_CONTEXT.md
  TSF/trustable/assumptions-of-use/AOU-14.md
  TSF/trustable/assumptions-of-use/AOU-17.md
  TSF/trustable/generated/AOU.md
  TSF/trustable/generated/JLEX.md
  TSF/trustable/generated/JLS.md
  TSF/trustable/generated/NJF.md
  TSF/trustable/generated/PJD.md
  TSF/trustable/generated/TA.md
  TSF/trustable/generated/TRUSTABLE.md
  TSF/trustable/generated/TT.md
  TSF/trustable/generated/WFJ.md
  TSF/trustable/generated/dashboard.md
  TSF/trustable/generated/graph
  TSF/trustable/generated/graph.svg
  TSF/trustable/generated/nav.md
  TSF/trustable/generated/trustable_report_for_Software.md
  TSF/trustable/statements/JLS-01.md
  TSF/trustable/statements/JLS-05.md
  TSF/trustable/statements/JLS-23.md
  TSF/trustable/statements/JLS-24.md
  TSF/trustable/statements/JLS-26.md
  TSF/trustable/tenets/TT-CHANGES.md
  TSF/trustable/tenets/TT-CONFIDENCE.md
  TSF/trustable/tenets/TT-CONSTRUCTION.md
  TSF/trustable/tenets/TT-EXPECTATIONS.md
  TSF/trustable/tenets/TT-PROVENANCE.md
  TSF/trustable/tenets/TT-RESULTS.md
Labels: tests, CI

#84 generate list of misbehaviours
  .github/workflows/publish_documentation.yml
Labels: M, CI

#86 Erik fix feedback
  .dotstop_extensions/references.py
  TSF/docs/concept.rst
  TSF/docs/introduction/index.rst
  TSF/scripts/clean_trudag_output.py
  TSF/scripts/generate_report.sh
  TSF/trustable/statements/JLS-04.md
Labels: documentation

#87 Revision 1 1 jk
  .dotstop.dot
  .dotstop_extensions/README.md
  .dotstop_extensions/references.py
  .dotstop_extensions/test_references.py
  TSF/docs/index.rst
  TSF/docs/introduction/index.rst
  TSF/trustable/assumptions-of-use/AOU-01.md
  TSF/trustable/assumptions-of-use/AOU-02.md
  TSF/trustable/assumptions-of-use/AOU-03.md
  TSF/trustable/assumptions-of-use/AOU-04.md
  TSF/trustable/assumptions-of-use/AOU-05.md
  TSF/trustable/assumptions-of-use/AOU-06.md
  TSF/trustable/assumptions-of-use/AOU-07.md
  TSF/trustable/assumptions-of-use/AOU-08.md
  TSF/trustable/assumptions-of-use/AOU-09.md
  TSF/trustable/assumptions-of-use/AOU-10_COMBINED.md
  TSF/trustable/assumptions-of-use/AOU-14.md
  TSF/trustable/assumptions-of-use/AOU-15.md
  TSF/trustable/assumptions-of-use/AOU-16.md
  TSF/trustable/assumptions-of-use/AOU-17.md
  TSF/trustable/assumptions-of-use/AOU-18.md
  TSF/trustable/assumptions-of-use/AOU-19.md
  TSF/trustable/assumptions-of-use/AOU-20.md
  TSF/trustable/assumptions-of-use/AOU-21.md
  TSF/trustable/assumptions-of-use/AOU-22.md
  TSF/trustable/assumptions-of-use/AOU-23.md
  TSF/trustable/assumptions-of-use/AOU-24.md
  TSF/trustable/assumptions-of-use/AOU-25.md
  TSF/trustable/assumptions-of-use/AOU-26.md
  TSF/trustable/assumptions-of-use/AOU-27.md
  TSF/trustable/expectations/JLEX-01.md
  TSF/trustable/expectations/JLEX-02.md
  TSF/trustable/no-json-faults/NJF-01.md
  TSF/trustable/no-json-faults/NJF-02.md
  TSF/trustable/no-json-faults/NJF-03.md
  TSF/trustable/no-json-faults/NJF-04.md
  TSF/trustable/no-json-faults/NJF-05.1.md
  TSF/trustable/no-json-faults/NJF-06.1.md
  TSF/trustable/no-json-faults/NJF-07.md
  TSF/trustable/no-json-faults/NJF-08.md
  TSF/trustable/no-json-faults/NJF-09.md
  TSF/trustable/no-json-faults/NJF-11.md
  TSF/trustable/no-json-faults/NJF-14.3.md
  TSF/trustable/no-parsing-faults/NPF-02.7.md
  TSF/trustable/no-parsing-faults/NPF-02.md
  TSF/trustable/no-parsing-faults/NPF-03.1.md
  TSF/trustable/no-parsing-faults/NPF-03.md
  TSF/trustable/no-parsing-faults/NPF-04.1.md
  TSF/trustable/no-parsing-faults/NPF-04.md
  TSF/trustable/no-parsing-faults/NPF-05.1.md
  TSF/trustable/no-parsing-faults/NPF-06.1.md
  TSF/trustable/statements/JLS-16.md
  TSF/trustable/well-formed-json/WFJ-06.md
Labels: documentation, L
